imports:
  - php

filter:
  excluded_paths: [vendor/*, tests/*]

build:
  dependencies:
    before:
      - touch database/database.sqlite
  #   after:
  #     - php artisan migrate

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    coverage:
      tests:
        override:
          - command: "make phpunit"
            coverage:
              file: "build/coverage.clover"
              format: "php-clover"
