imports:
  - php

filter:
  excluded_paths: [vendor/*, tests/*]

build:
  environment:
    # php: "7.1"
    # mysql: "5.7"
    # node: "8.1"
    # hosts:
    #   laravel.dev: "127.0.0.1"
    variables:
      APP_KEY: "base64:bN9CCzfNsJhDhPWpyZxbZ74A1FzfFkfjb8K1zYwngs8="
      # APP_ENV: "testing"
      # DB_HOST: "127.0.0.1"
      # DB_DATABASE: "scrutinizer"
      # DB_USERNAME: "root"
      # DB_PASSWORD: ""
      DB_CONNECTION: "sqlite"

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    tests-and-coverage:
      tests:
        override:
          - command: "make phpunit"
            coverage:
              file: "build/coverage.clover"
              format: "clover"
          # - command: "vendor/bin/phpunit --coverage-clover=coverage"
          #       coverage:
          #           file: "build/coverage.clover"
          #           format: "clover"
