imports:
  - php

filter:
  excluded_paths: [vendor/*, tests/*]

build:
  environment:
    variables:
      # APP_KEY: "base64:OYl4Bk9ekouOUIRXyeTD0FVi+cJ9D+HMyDJBgSBSUuI="
      # APP_ENV: "testing"
      DB_DATABASE: "scrutinizer"
  dependencies:
    before:
      - touch scrutinizer.sqlite
  #   after:
  #     - php artisan migrate

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    tests-and-coverage:
      tests:
        override:
          - command: "make phpunit"
            coverage:
              file: "build/coverage.clover"
              format: "php-clover"
