imports:
  - php

filter:
  excluded_paths: [vendor/*, tests/*]

build:
  environment:
    variables:
      DB_DATABASE: "database.sqlite"

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

  tests-and-coverage:
    tests:
      override:
        - command: "make phpunit"
          coverage:
            file: "build/coverage.clover"
            format: "php-clover"
